//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwareQualityPrediction.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoftwareQualityPrediction.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation Function.
        /// </summary>
        public static string ActivationFunctionCaption {
            get {
                return ResourceManager.GetString("ActivationFunctionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add &gt;&gt;.
        /// </summary>
        public static string AddCaption {
            get {
                return ResourceManager.GetString("AddCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bipolar Sigmoid.
        /// </summary>
        public static string BipolarSigmoidCaption {
            get {
                return ResourceManager.GetString("BipolarSigmoidCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string BrowseCaption {
            get {
                return ResourceManager.GetString("BrowseCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected document must contain the following columns: {0}..
        /// </summary>
        public static string ColumnsToBeSelectedCaption {
            get {
                return ResourceManager.GetString("ColumnsToBeSelectedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross-Validation K Parameter.
        /// </summary>
        public static string CrossValidationParameterCaption {
            get {
                return ResourceManager.GetString("CrossValidationParameterCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} field is required.
        /// </summary>
        public static string FieldIsRequiredValidationMessage {
            get {
                return ResourceManager.GetString("FieldIsRequiredValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string FileFieldCaption {
            get {
                return ResourceManager.GetString("FileFieldCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To Testing.
        /// </summary>
        public static string GoToTestingCaption {
            get {
                return ResourceManager.GetString("GoToTestingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden Layers.
        /// </summary>
        public static string HiddenLayersCaption {
            get {
                return ResourceManager.GetString("HiddenLayersCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the amount of neurons in each hidden layer. Each value represents the amount of neurons in a single hidden layer. Values are separated by &quot;;&quot;. Enter as many values as many hidden layers you want. Example: 10;3;4 is a specification for 3 hidden layers, with 10 neurons on the first hidden layer, 3 on the second and 4 on the third..
        /// </summary>
        public static string HiddenLayersDescription {
            get {
                return ResourceManager.GetString("HiddenLayersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Column.
        /// </summary>
        public static string IdColumnCaption {
            get {
                return ResourceManager.GetString("IdColumnCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Variables.
        /// </summary>
        public static string InputVariablesCaption {
            get {
                return ResourceManager.GetString("InputVariablesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid hidden layers format.
        /// </summary>
        public static string InvalidHiddenLayersFormatValidationMessage {
            get {
                return ResourceManager.GetString("InvalidHiddenLayersFormatValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learning Rate.
        /// </summary>
        public static string LearningRateCaption {
            get {
                return ResourceManager.GetString("LearningRateCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learning Rate must be a positive real number.
        /// </summary>
        public static string LearningRateValidationMessage {
            get {
                return ResourceManager.GetString("LearningRateValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location .
        /// </summary>
        public static string LocationToSaveCaption {
            get {
                return ResourceManager.GetString("LocationToSaveCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string MenuCaption {
            get {
                return ResourceManager.GetString("MenuCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Error must be a positive real number.
        /// </summary>
        public static string MinErrorValidationMessage {
            get {
                return ResourceManager.GetString("MinErrorValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Error.
        /// </summary>
        public static string MinimumErrorCaption {
            get {
                return ResourceManager.GetString("MinimumErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neural Network Name.
        /// </summary>
        public static string NeuralNetworkNameCaption {
            get {
                return ResourceManager.GetString("NeuralNetworkNameCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neural Network Path.
        /// </summary>
        public static string NeuralNetworkPathCaption {
            get {
                return ResourceManager.GetString("NeuralNetworkPathCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string NextCaption {
            get {
                return ResourceManager.GetString("NextCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Epochs must be a positive number greater than 0.
        /// </summary>
        public static string NoEpochsValidationMessage {
            get {
                return ResourceManager.GetString("NoEpochsValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No item selected for {0}.
        /// </summary>
        public static string NoItemSelectedValidationMessage {
            get {
                return ResourceManager.GetString("NoItemSelectedValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Epochs.
        /// </summary>
        public static string NumberOfEpochsCaption {
            get {
                return ResourceManager.GetString("NumberOfEpochsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Columns.
        /// </summary>
        public static string OutputColumnsCaption {
            get {
                return ResourceManager.GetString("OutputColumnsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Variables.
        /// </summary>
        public static string OutputVariablesCaption {
            get {
                return ResourceManager.GetString("OutputVariablesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path does not exist.
        /// </summary>
        public static string PathNoExistValidationMessage {
            get {
                return ResourceManager.GetString("PathNoExistValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt; Remove.
        /// </summary>
        public static string RemoveCaption {
            get {
                return ResourceManager.GetString("RemoveCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save settings.
        /// </summary>
        public static string SaveSettingsCaption {
            get {
                return ResourceManager.GetString("SaveSettingsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Neural Network Parameters.
        /// </summary>
        public static string SelectAnnParametersCaption {
            get {
                return ResourceManager.GetString("SelectAnnParametersCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Hidden Layers.
        /// </summary>
        public static string SelectHiddenLayersCaption {
            get {
                return ResourceManager.GetString("SelectHiddenLayersCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Input Variables.
        /// </summary>
        public static string SelectInputVariablesCaption {
            get {
                return ResourceManager.GetString("SelectInputVariablesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select The Neural Network.
        /// </summary>
        public static string SelectNNForTestingCaption {
            get {
                return ResourceManager.GetString("SelectNNForTestingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Output Columns.
        /// </summary>
        public static string SelectOutputColumnsCaption {
            get {
                return ResourceManager.GetString("SelectOutputColumnsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Output Variables.
        /// </summary>
        public static string SelectOutputVariablesCaption {
            get {
                return ResourceManager.GetString("SelectOutputVariablesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Termination Condition.
        /// </summary>
        public static string SelectTerminationConditionCaption {
            get {
                return ResourceManager.GetString("SelectTerminationConditionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Testing Data File.
        /// </summary>
        public static string SelectTestingDataFileCaption {
            get {
                return ResourceManager.GetString("SelectTestingDataFileCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Training Data File.
        /// </summary>
        public static string SelectTrainingDataFileCaption {
            get {
                return ResourceManager.GetString("SelectTrainingDataFileCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Validation Parameters.
        /// </summary>
        public static string SelectValidationParametersCaption {
            get {
                return ResourceManager.GetString("SelectValidationParametersCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must upload a file that contains the following input valiables: {0}..
        /// </summary>
        public static string SelectVariablesCaption {
            get {
                return ResourceManager.GetString("SelectVariablesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet.
        /// </summary>
        public static string SheetCaption {
            get {
                return ResourceManager.GetString("SheetCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should be exaclty {0} items selected.
        /// </summary>
        public static string ShouldBeExactlyValidationMessage {
            get {
                return ResourceManager.GetString("ShouldBeExactlyValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sigmoid.
        /// </summary>
        public static string SigmoidCaption {
            get {
                return ResourceManager.GetString("SigmoidCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Testing.
        /// </summary>
        public static string StartTestingCaption {
            get {
                return ResourceManager.GetString("StartTestingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Training.
        /// </summary>
        public static string StartTrainingCaption {
            get {
                return ResourceManager.GetString("StartTrainingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing.
        /// </summary>
        public static string TestingCaption {
            get {
                return ResourceManager.GetString("TestingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing completed! Results are in the uploaded file..
        /// </summary>
        public static string TestingCompletedCaption {
            get {
                return ResourceManager.GetString("TestingCompletedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neural network successfuly trained!.
        /// </summary>
        public static string TrainingCompletedMessage {
            get {
                return ResourceManager.GetString("TrainingCompletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Data.
        /// </summary>
        public static string TrainingDataCaption {
            get {
                return ResourceManager.GetString("TrainingDataCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Parameters.
        /// </summary>
        public static string TrainingParametersCaption {
            get {
                return ResourceManager.GetString("TrainingParametersCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Result.
        /// </summary>
        public static string TrainingResultCaption {
            get {
                return ResourceManager.GetString("TrainingResultCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload File.
        /// </summary>
        public static string UploadFileCaption {
            get {
                return ResourceManager.GetString("UploadFileCaption", resourceCulture);
            }
        }
    }
}
